name: doctor_suplementos
description: "App de asesoramiento técnico para socios de 4Life."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Librería de Iconos (Estándar de Flutter)
  cupertino_icons: ^1.0.8

  # Libreria de compartir contenido
  share_plus: ^13.1.0

  # Inteligencia Artificial: Gemini 3.1
  google_generative_ai: ^0.4.7
  
  # Firebase: Conexión y Base de Datos
  firebase_core: ^4.9.0
  cloud_firestore: ^6.4.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4 # Añade esta línea

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # sdk mínimo para iconos adaptativos
  adaptive_icon_background: "#1A237E" # El color azul de tu app
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  # Activa el diseño Material Design para botones y campos de texto
  uses-material-design: true
