name: doctor_suplementos
description: "App de asesoramiento técnico para socios de 4Life."
publish_to: 'none'

version: 1.3.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Libreria de compartir contenido
  share_plus: 10.1.4
  pdf: ^3.12.0
  http: ^1.2.0
  qr_flutter: ^4.1.0
  lottie: ^3.1.3

  # Inteligencia Artificial: Gemini 3.1
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0
  
  # Firebase: Conexión y Base de Datos
  firebase_core: ^4.9.0
  cloud_firestore: ^6.4.1
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  record: ^6.2.1
  path_provider: ^2.1.5
  firebase_remote_config: ^6.5.1
  package_info_plus: ^9.0.1
  flutter_tts: ^4.2.3
  url_launcher: ^6.3.2
  dio: ^5.4.0
  open_file: ^3.3.2
  permission_handler: ^11.3.0
  video_player: ^2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4 # Añade esta línea

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.webp"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.webp"
  web:
    generate: true
    image_path: "assets/icon.webp"
    background_color: "#FFFFFF"
    theme_color: "#1A237E"
  windows:
    generate: true
    image_path: "assets/icon.webp"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon.webp"

flutter:
  # Activa el diseño Material Design para botones y campos de texto
  uses-material-design: true
  assets:
    - .env
    - assets/icon.webp
    - assets/fonts/
    - assets/lottie/
    - assets/productos/productos-ec/
    - assets/productos/productos-eu/
    - assets/testimonios/
